[package]
authors = ["Without Boats <woboats@gmail.com>"]
name = "configure"
version = "0.1.0"

[dependencies]
erased-serde = "0.3.3"
heck = "0.3.0"
serde = "1.0.21"
toml = "0.4.5"

[dev-dependencies]
serde_derive = "1.0.21"

[dev-dependencies.test-setup]
path = "./test-setup"

[workspace]
