[package]
name = "configure"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]

[dependencies]
toml = "0.4.5"
serde = "1.0.15"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"
